### PR TITLE
Fix typo in name

### PR DESCRIPTION
**Pull request by matthijskooijman**
I just noticed you made a small typo in my name, so here's a fix ;-)

### CODE REVIEW

**Comment by jonkerj** [comment]
Wow, I feel ashamed, sorry for that. Merged!

**Comment by jonkerj** [comment]
The CD is not happy yet, I'll check/fix this tomorrow

**Comment by jonkerj** [comment]
It's fixed now, thanks for your contribution!

**Comment by matthijskooijman** [comment]
> Wow, I feel ashamed, sorry for that. Merged!

No worries, thanks for fixing (and for writing this library!).

**Pull request merged**
